### ISSUE TITLE
[MEETING] - Identity Kickoff Wed 04-Nov-2020 19:00 (UTC)

### ISSUE THREAD

**Issue by huhn511** [iota-community/X-Team_IOTA_Identity#10]
# X-Team Identity Kickoff 

# Time
**UTC** Wed 04-Nov-2020 19:00 (07:00 PM):

Or in your local time:

https://www.timeanddate.com/worldclock/fixedtime.html?msg=2020-11-04&iso=20201104T19

# Links

Meeting Notes: https://hackmd.io/@WZdHn6o0TmiYck3zlENRsw/By2hVBI8v

# Agenda

* Welcome
* Introduction Identity.rs
* Groups and Goals

# Invited

* Open for Everyone

## Observers/Guests

Attend the meeting as a guest by calling into Jitsi, using the links below. If you will be attending as a guest, please comment on this issue to let us know you'll be joining.
_YouTube stream will follow_

# Notes

The agenda comes from issues labeled with xt-agenda across all of the IOTA Experience Team repositories in the iota-community org. Please label any additional issues that should be on the agenda before the meeting starts.

# Joining the meeting

* Link for participants: https://meet.jit.si/X-TeamsID
Password in the x-Team Discord channel (x-team-identity)

# Invitees

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by BenRoyce-Society2-com** [comment]
nov 4 is wednesday (says tue ^^^)

**Comment by BenRoyce-Society2-com** [comment]
hi, can i get a link as a guest? thanks

"If you will be attending as a guest, please comment on this issue to let us know you'll be joining."

**Comment by tommyyama2020** [comment]
Hi, identity.ts is going to be depreciated?

**Comment by huhn511** [comment]
Hey @tommyyama2020,

yes - identity.ts is going to be deprecated. There is a binding to Javascript/Typescript (called WASM) which will be released soon :) 

You can ask for early access in the x-team-identity channel in Discord.

**Comment by huhn511** [comment]
@BenRoyce-Society2-com 

Links to the meetings will be published in the `x-team-identity `channel in Discord.
