### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by Aconitin** [iota-community/X-Team_IOTA_Identity#11]
# X-Team Initiative Application

## Whats your Discord Handle
Aconitin#1833

## I want to participate as
- [x] Developer (Jelle made me tick this box pls send help)
- [ ] Designer
- [x] Tester
- [ ] Writer
- [x] That guy that always complains about a lack of features, yet mysteriously vanishes when asked about his own contributions

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. Programming in various languages (Lua, Python, JavaScript/NodeJs, C++, learning Rust atm, ...)
2. Teaching programming in those languages
3. Can cook minute rice in 58 seconds
4. Quite good knowledge of W3C's DID & VC stuff, as I implemented it myself already

## Describe yourself in a few sentences
Just some random guy, I suppose.

## Why do you like to join the Identity X-Team? 
I use IOTA Identity within my company, so it only makes sense to participate a bit.

**Comment by antonionardella** [comment]
Added! 🥳
