### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by eike-hass** [iota-community/X-Team_IOTA_Identity#12]
# X-Team Initiative Application

## Whats your Discord Handle
- 31k3#8053

## I want to participate as
- [ x] Developer
- [ ] Designer
- [ ] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. JS / Typescript / Node

## Describe yourself in a few sentences
- Developer interested in all things DLT and especially DID.

## Why do you like to join the Identity X-Team? 
-To get in touch with the IOTA community

**Comment by antonionardella** [comment]
Added to the GoShimmer X-Team!
Welcome!
