### ISSUE TITLE
[GOAL] C bindings

### ISSUE THREAD

**Issue by kuhlmannmarkus** [iota-community/X-Team_IOTA_Identity#14]
# Goal Title
**Priority: (1)**
C bindings
## Key results
1. - [C bindings]
2. - [some examples decribing typical use cases]

# Team
IOTA Identity - IOTA Experience Team

### X-Team members
TBD

### IOTA Foundation member
TBD. Hi, @oopsmonk ;-)

# Additional Information

# Governance
Please use the following emoji reactions in this post to indicate:
:+1: - Participating
:heavy_plus_sign: - Add my vote

**Comment by huhn511** [comment]
I started with a simple setup and added the feedback from @bernardoaraujor to make it easy usable for C developers.
The readme should explain the setup.

Now it's time to bind the functions! 

Anyone interested to help? :)
