### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by fiNYvo** [iota-community/X-Team_IOTA_Identity#15]
# X-Team Initiative Application

## Whats your Discord Handle
- 619082380648513557

## I want to participate as
- [ X] Developer
- [ ] Designer
- [ ] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. Python
2. little, little bit rust
3. little, little bit go
4. your skill 4

## Describe yourself in a few sentences
- I am 31 years old, im from Germany - Cologne and i´m very interested in Iota. 

## Why do you like to join the Identity X-Team? 
- I think DID can change so many things in the world. It gives me the chance to be a part of it.

**Comment by antonionardella** [comment]
Welcome to the X-Team!
