### ISSUE TITLE
[MEETING] - (2021-02-01) Weekly Meeting 

### ISSUE THREAD

**Issue by huhn511** [iota-community/X-Team_IOTA_Identity#18]
# Time

Mondays at 20:00 (8PM) - 21:00 (9PM) CET

# Notes

Meeting Minutes: < Insert hackmd.io Link >

# Agenda

Extracted from xt-agenda labelled issues and pull requests from the IOTA Experience Team prior to the meeting.

Please use the commend section below to suggest new topics. 

* Point 1
* Point 2
* Point 3

# Invited

* Identity Experience Team

# Notes

The agenda comes from issues labelled with xt-agenda across all of the IOTA Experience Team repositories in the iota-community org. Please label any additional issues that should be on the agenda before the meeting starts.

# Joining the meeting

Meeting will be in the Discord Experience Voice Chat

# Invitees

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by Aconitin** [comment]
Hey!
For the agenda: Depending on who's attending, I'd suggest having a talk about ongoing projects of each participant.
I'd also add a "Anyone else who is interested" to the "invited" section :)
