### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by ggreeve** [iota-community/X-Team_IOTA_Identity#29]
# X-Team Initiative Application

## Whats your Discord Handle
- [gman_IoTangle#7856]

## I want to participate as
- [] Developer
- [X ] Designer
- [X] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. I'm a Industrial Controls engineer, So I'm very experience in plant automation, SCADA and PLC programming.
2. I build small Node-Red based IoT edge 4G devices for customers, now developing custom embedded modules with basic C++ coding

## Describe yourself in a few sentences
- [My name is Gerhard, I live in the USA. I work for a large corporation where I am hands on with designing and configuring factory automation systems. As a hobby I play around with IIoT. I recently started developing custom 4G edge devices to allow customers to get legacy industrial controllers connected to the cloud using 4G. I have been following IOTA for many years and I feel this is the best DLT that can provide the data integrity we need in my industry for supply chain, M2M etc]

## Why do you like to join the Identity X-Team? 
- [I feel that my IIoT devices can greatly benefit if the device can have a DiD and can use Verifiable Credentials to prove that the data is unadulterated, this solving some of the garbage-in-garbage-out problems.
- Since I plan to incorporate IOTA Streams into my devices, I feel that discussing IOTA Identities with the group I can learn how to best apply this technology to my projects and I hope that I can also bring some value to the group with some actual products that can use IOTA Streams. ]

**Comment by antonionardella** [comment]
Added!

Welcome to the X-Team!
