### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by Cryptec** [iota-community/X-Team_IOTA_Identity#3]
# X-Team Initiative Application

## Whats your Discord Handle
- [Martin N#8948]

## I want to participate as
- [x] Developer
- [x] Designer
- [x] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. JavaScript
2. Affinity Designer

## Describe yourself in a few sentences
- [Passioned about IOTA and working on a view Projects within the ecosystem. Im not a Professional coder, but want to learn continuous.]

## Why do you like to join the Identity X-Team? 
- [I love digital ID´s, want to contribute to the ecosystem and learn some new stuff. Also interested in using this DID at Deposy later.]

**Comment by antonionardella** [comment]
Added! 🥳
