### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by m-renaud** [iota-community/X-Team_IOTA_Identity#31]
# X-Team Initiative Application

## Whats your Discord Handle
- m-renaud#5261

## I want to participate as
- [x] Developer
- [ ] Designer
- [ ] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)

- Backend infrastructure engineering: C++, Rust, Haskell, Java
- Frontend infrastructure engineer (some React and Vue)

## Describe yourself in a few sentences

My name is Matt, I'm a Canadian living in California working at [large-tech-company]. I've been working for 7 years professionally as a software engineer on large, scalable infrastructure (frontend and backend). I've made some contributions to open source before, such as documentation for some of Haskell's standard container libraries (https://haskell-containers.readthedocs.io), and optimizations and API improvements to the unordered-container library (https://github.com/haskell-unordered-containers/unordered-containers/pulls?q=is%3Apr+is%3Aclosed+author%3Am-renaud). I'm care strongly about privacy and democratizing technology. I'm also a programming language design enthusiast :)

## Why do you like to join the Identity X-Team?

I've been following the IOTA project for several years and love what the IOTA Foundation and community have been doing. With respect to Identity, I'm really excited about the use of VCs in the healthcare space, specifically around user privacy of health records, and the ability to integrate verified records into research. I'm also an infrastructure engineer at heart who likes to build robust, safe, and well-documented APIs to enable others to build great products.

**Comment by antonionardella** [comment]
Hello and Welcome to the X-Team!
