### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by andreapenza** [iota-community/X-Team_IOTA_Identity#32]
# X-Team Initiative Application

## Whats your Discord Handle
- [blank#3602]

## I want to participate as
- [x] Developer
- [ ] Designer
- [ ] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. HTML, CSS, Javascript
2. ReactJS/Material UI
3. NodeJS
4. Docker, Nginx
5. Iota Mam

I had the chance to work on different projects making use of the IOTA Mam technology as the core tech. As a Fullstack developer I was directly involved in the planning and the coding of the different solutions.

## Describe yourself in a few sentences
- I'm driven by curiosity and I like challenges and getting out of my comfort zone, whichever field this concept can be applied to. 
## Why do you like to join the Identity X-Team? 
- Being part of a company which is highly interested to the IOTA world, primarily to learn and consequently be able to use this new knowledge and skills to work on fun and interesting projects related to the Iota Digital Identity,

**Comment by antonionardella** [comment]
Welcome to the X-Team!
