### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by cayasso** [iota-community/X-Team_IOTA_Identity#33]
# X-Team Initiative Application

## What's your Discord Handle
- cayasso#5172

## I want to participate as
- [X] Developer
- [ ] Designer
- [ ] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
1. Front end: Javascript, React, NextJS, Websockets
2. Back end: NodeJS, AWS Lambda, Serverless Framework, AWS Cloud, Google Cloud, MongoDB, Neo4J
3. Mobile: React Native, Expo, Websocket

## Describe yourself in a few sentences
My name is Jonathan Brumley from Costa Rica, I am a Software Engineer with more than 15 years of experience working and advocating Web Technologies for large and small startup companies, such as HP, LLBean, Autotrader, Agenix, OR Tracker, Regatta. I have experience developing mobile and real-time applications and in my journey, I have contributed to Open Source with various projects (Rooms, Mongo-Oplog, Cacheman, Primus.IO, Advent, and some others) you can check [here on github](https://github.com/cayasso). I am very passionate about new technologies that can change the world and make it a better place. I am also the founder of [Spry](https://spry.cr), [Culto](https://culto.app) and principal developer of [Costa Rica Goverment Health Pass](https://salud.go.cr)

## Why do you like to join the Identity X-Team? 
I've been following the IOTA project since it was started years ago and love what the IOTA Foundation and community have been doing, however, I would like to get more involved and actually start learning, building, and collaborating by bringing IOTA Identity into some of my projects and explore new ideas.
I am very excited to become part of the great community that is driving a change with the IOTA revolution.

**Comment by antonionardella** [comment]
Hello and welcome to the X-Team!
