### ISSUE TITLE
[Application] - Hello Team, I'm Connor

### ISSUE THREAD

**Issue by ConnorCink** [iota-community/X-Team_IOTA_Identity#35]
# X-Team Initiative Application

## Whats your Discord Handle
- poster#5787

## I want to participate as
- [ X] Developer
- [ X] Designer
- [ X] Tester
- [ X] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. Java
2. AWS
3. Jira/Intent Setup
4. Go

## Describe yourself in a few sentences
- I’m an Industrial Engineering undergrad turned Software Engineer turned Product Lead. I've worked in the fintech world since graduating in 2017. I think IOTA is the future and want to help build it.

## Why do you like to join the Identity X-Team? 
- I think this technology has incredible implications and lots of usecases. One of them being a notary-style onboarding process to a digital identity group.

**Comment by antonionardella** [comment]
Welcome to the team!
