### ISSUE TITLE
Application 

### ISSUE THREAD

**Issue by pascalgottret** [iota-community/X-Team_IOTA_Identity#38]
**X-Team Initiative Application**

**Whats your Discord Handle**
instrumental#9806

**I want to participate as**
[ ] Developer
[ ] Designer
[X] Tester
[X] Writer

**What are your skills? (Programming languages and/or other tools)**
Please arrange your skills along with experience.
SAP ABAP

**Describe yourself in a few sentences**
I work as an SAP ERP application manager in Switzerland for a global trading company and Tier-1 supplier in the automotive sector. I design and customize business processes. 
(btw: I studied the W3C SSI Standard carefully).

**Why do you like to join the Identity X-Team?**
As daily confronted with the challenges in the global supply chain I truly believe that DLT will make the global supply chain more efficient. DID is one of the most important parts in the DLT space and will help companies and individuals in a tremendous way. As Switzerland is discussing  to introduce an e-ID ecosystem based on SSI as this application is being written, I want to participate in DID-projects and help IOTA Identity to become a standard.

**Comment by antonionardella** [comment]
Application accepted and added in Discord!
