### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by oostech** [iota-community/X-Team_IOTA_Identity#4]
# X-Team Initiative Application

## Whats your Discord Handle
Oostech#6884

## I want to participate as
- [x] Developer
- [ ] Designer
- [ ] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. C/C++
2. Java
3. Javascript
4. Python

## Describe yourself in a few sentences
Software developer from Hamburg working on a couple of IOTA projects

## Why do you like to join the Identity X-Team? 
To eventually integrate DID into my project Espiota

**Comment by antonionardella** [comment]
Added! 🥳
