### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by kuhlmannmarkus** [iota-community/X-Team_IOTA_Identity#5]
# X-Team Initiative Application

## Whats your Discord Handle
- herrkpunkt#3501

## I want to participate as
- [ ] Developer
- [X] Designer
- [X] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. C/C++
2. Rust

## Describe yourself in a few sentences
- Developer and consultant from NRW.

## Why do you like to join the Identity X-Team? 
- We at SOCIETY2 want to have a standardized solution and would love to participate.

**Comment by antonionardella** [comment]
Added! 🥳
