### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by demichele** [iota-community/X-Team_IOTA_Identity#6]
# X-Team Initiative Application

## Whats your Discord Handle
- Carpincho Dem#0315

## I want to participate as
- [X ] Developer
- [ ] Designer
- [X ] Tester
- [X ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. Project Management
2. Fullstack Dev
3. Community Builder
4. Embedded Devices

## Describe yourself in a few sentences
- Argentinian/Italian Full Stack Web Developer & Entrepreneur. Sysadmin, Webservers & HA on Unix environments. DLT enthusiast since 2013. Head of IOTA Evangelist Network, Director of Active Learning at IOT1 Academy, XDK2MAM/IOT2TANGLE Founder. 

## Why do you like to join the Identity X-Team? 
- Because DID is a key feature needed to have our vision working

**Comment by antonionardella** [comment]
Added! 🥳
