### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by Thoralf-M** [iota-community/X-Team_IOTA_Identity#7]
# X-Team Initiative Application

## Whats your Discord Handle
- Thoralf#3558

## I want to participate as
- [x] Developer
- [ ] Designer
- [ ] Tester
- [ ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. Javascript
2. Rust

## Describe yourself in a few sentences
- IOTA enthusiast and community dev

## Why do you like to join the Identity X-Team? 
- See how identity will be used, help with code and maybe update identity.rs to make stuff easier to use

**Comment by antonionardella** [comment]
Added! 🥳
