### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by marektichy** [iota-community/X-Team_IOTA_Identity#8]
# X-Team Initiative Application

## Whats your Discord Handle
- Marek Tichy#7429

## I want to participate as
- [ x ] Developer
- [ o ] Designer
- [ x ] Tester
- [ x ] Writer

## What are your skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. Debian sysadmin
2. Drupal expert
3. Javascript/VueJS/NodeJS coder
4. PHP programmer

## Describe yourself in a few sentences
- I hold a masters degree in mathematics and computer science from Charles University Prague. I work at GreenNet (https://www.greennet.org.uk/), a not-for-profit collective established 1985, providing internet services, web design and hosting to supporters of peace, the environment and human rights, member of the Association for Progressive Communication (https://www.apc.org). I like to play the guitar and ride my bike. I have an 11 years old daughter, Miriam, for whom I would love to create a safer and trustworthy Internet by adding the badly missing identity layer.

## Why do you like to join the Identity X-Team? 
- I believe IOTA or more precisely the Tangle has a unique and ideal set of features (no fees and no miners) for a global identity system, as opposed to Sovrin, UPort and the likes. I have been participating in the identity discussion on discord for a couple of years now and I welcome recent appointment of Jelle as a lead of IF identity efforts. I would like to contribute where I can and also want to learn about the decentralized identity standards.

**Comment by antonionardella** [comment]
Added! 🥳
